# Generated by Django 4.1.7 on 2023-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_date_create_alter_project_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
