# Generated by Django 4.1.7 on 2023-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_article_date_update_alter_project_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
