version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://username:passwd!@pg:5432/blog
      CONFIG_NAME: ProductionConfig

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data: